### ISSUE TITLE
Extension not working in Edge browser and local GitLab Instance

### ISSUE THREAD

**Issue by xChillout** [puyt/chrome-gitlab-enhancer#25]
I have specified the local instance URL as described but the extension does not work in Edge Browser Version 127.0.2651.74

![image](https://github.com/user-attachments/assets/8768a318-f588-404b-9816-7f66a8ba7799)

**Comment by puyt** [comment]
Again sorry for the late response :sweat_smile: 

I guess it probably has something to do with the trailing slash, can you try removing the URL from the instance input, save it and re-add it without the trailing slash?

**Comment by xChillout** [comment]
thanks to the suggestions. tried it but it does not work. root cause bight be the same as for this addin https://gitlab.com/potato-oss/gitlab-details-sidebar/-/issues/57. however the following addin works fine with custom/lokal instance URL https://github.com/tavyandy97/span-tree

**Comment by puyt** [comment]
@xChillout The new version has been accepted
